i18next/react-i18next

src/translate.js

When you wrap component in translate, you loose any reference to it.
This is for example required when you're doing server-side rendering, and Component defines which actions to do to prefetch data.
Same approach is used in react-redux [connect wrapper](https://github.com/reactjs/react-redux/blob/v4.4.0/src/components/connect.js#L288)

Added WrappedComponent property to translate wrapper

---

bower.json

Hello,
I found there was something missing in the bower.json, i.e. missing comma near the 'bin/', this is going to make bower installation be failed. Would you please fix it?? Thank you for this great works. :)

Missing comma in bower.json

---

README.md

Adapted from the [sample/boilerplate](https://github.com/simpleblack/react-redux-universal-hot-example) example, thought this might be useful to add to the `README` since it's not trivial how to use the express middleware together with `react-i18next`.
Not sure if this is the best solution, but it does the job well enough!

Add express middleware integration explanation

---

src/translate.js

It looks like one issue from here https://github.com/i18next/react-i18next/issues/6
```
export const Menu = ({t}) => (
<div>{t('hello')}</div>
);
export default translate(['menu'])(Menu);
```
When I use HMR, this code will throw `t is not defined` on reload. It seems to happen because `t` is a local var of `translate` decorator and it is not preserved between reloads. So I set it as class property and it works as expected.

Fix t is not defined when hot reload

---

src/translate.js

I've been experiencing errors with hot module reloading with react-i18next. https://github.com/i18next/react-i18next/pull/112 helped; I don't get an error immediately on the hot module reload anymore.
However, I still do get an error when a hot module reload occurs, and I then do something which mounts or unmounts a translated component (route change, for instance).
Error is either
- Cannot read property 'loadNamespaces' of undefined (https://github.com/i18next/react-i18next/issues/62)
- Cannot read property 'off' of undefined
depending on whether componentWillMount or componentWillUnmount occurs first.
Cause and fix are the same as https://github.com/i18next/react-i18next/pull/112, just with the i18n local variable this time.

Fix i18n is not defined on component mount/unmount after hmr

---

src/interpolate.js

I mentioned in #157 that it would be nice to receive a warning if no matching prop was provided during interpolation. I noticed that if you use `i18n.t` to try and translate a value that has a variable in it you get the following warning 
```
i18next::interpolator: missed to pass in variable test for interpolating Some value {{test}}
```
I added a basic conditional check that `this.props[match]` actually exists. If it doesn't it calls `this.i18n.services.logger.warn` and essentially mimic the exact same behavior as if you had used that translation with just the standard `i18n.t` function. 
First, I appreciate the work you guys have done. This is definitely the most enjoyable i18n software I have found. Second, I have not committed to OSS much, so forgive me if this is a naive solution. If …

Added conditional warning  on unmatched variable during interpolation

---

src/translate.js

Hello, `this.i18n.store` prop is not always ready/defined to the time when component is loaded. I'm using redux and it occurs with me after React 15.2.1

Fix bug with undefined store in translate component

---

README.md
example/app/components/View.js
example/locales/en/common.json
src/interpolate.js

Discussion in #189
Usage:
<Interpolate i18nKey='foo' useDangerouslySetInnerHTML={true} />
TODO:

Added an option of using the <Interpolate /> with a raw HTML

---

src/interpolate.js

Hi. There doesn't appear to be a way to customize the `className` prop set on the parent for interpolated components. This is a very naive implementation as I'm not familiar with all of the considerations that need to be made, but I figured it'd be good enough as a starting point for a discussion.

Support classnames on parents of interpolated components

---

.travis.yml
README.md
package.json

Hi, 
I have added code coverage trigger on travis after a success. Then the result of the coverage is pushed on coveralls.
I have forgotten last time to add badges to expose code quality to visitors. Here it is 
Could you please just activate the repository on coveralls and merge this please ?

chore: add coverage test to travis + badges

---

src/translate.js

Useful feature that makes using `translate` HOC easier to use without a provider.  Similar to react-redux: https://github.com/reactjs/react-redux/blob/master/src/components/connect.js#L83

Accept i18n context from props or context in translate wrapper

---

package.json

fix typo in amd build
by the way, I struggled to make npm build version of react-i18n to work with amd format.
When I use umd version with requirejs (ie. `define('react-i18n', function(reactI18n) {})` ), reactI18n is undefined.
Do you think we could also add `npm run build:amd` to the main build task ?

fix amd build

---

README.md

Since JSON does not allow comments, the syntax highlighter was acting a little weird for a block of code contained in the readme file. 
This PR fixes this, by changing the syntax highlighter language from JSON to JS. See images below.
**Before:**
**After:**

README - Use js instead of json for syntax highlighting

---

__tests__/translate-test.js
src/translate.js

There is a new feature added to pass i18n as a prop (for example using DI) but React emits a warning (Required context type i18n is missing)
References #203

Suppresses required context type warning if passing i18n as a prop

---

README.md

Probably not the best explanation (or any) of why this works...I did a bit of searching but couldn't find an exact explanation of how Typescript `export default` is different from regular ES `export default`

typescript tip

---

src/translate.js

There were two minor problems for react-i18next to work with TypeScript. First of all options and options.react might be undefined (on initialization). Then also it might be that if wait is set "true" in props, that there's indefinite wait if i18n doesn't get "initialized" signal through.

Fix react-i18next to work with TypeScript

---

src/translate.js

I have now tested that the problem originally (to need this workaround) was because of misuse of i18next initialization.
The updated code is at:
https://github.com/jussikinnula/react-starter/tree/typescript-i18next

Remove workaround to set ready if there was no initialized signal

---

package.json

jsnext:main is not supported in webpack (since webpack2).
For reference: https://github.com/webpack/webpack/issues/1979

Expose ES2015 modules as module in package.json

---

CHANGELOG.md
src/trans.js

This makes it possible to set className or other attributes on the generated parent component. For example you can do use:
```html
<Trans i18nKey="welcome.title" parent="h2" className="highlight">
Welcome to your new page.
</Trans>
```
to generate:
```html
<h2 class="highlight">Welcome to your new page</h2>
```

Pass extra Trans props to parent component

---

src/Trans.js
test/trans.render.spec.js
test/trans.spec.js

Currently, Trans uses i18n and t props when provided, but also passes them down to the rendered HTML element causing an error.
This PR does the following:
- Adds i18n and t propTypes
- Moves logic that determines which i18n and t to use from constructor to render
- Ensures i18n and t props don't get passed to the HTML element

Support passing i18n and t as Trans props

---

package.json

Recommended by the prop-types package: https://github.com/facebook/prop-types#how-to-depend-on-this-package

Change prop-types from a peer dependency to a normal dependency

---

src/I18n.js
test/I18n.spec.js

Fixes #324 
I'm adding line notes with questions 👍

Pre-check namespaces to avoid unnecessary initial `null` render

---

test/i18n.render.spec.js

The component appeared to have some test coverage but was not directly
tested. This suite can be expanded to include more tests.
Aside: I've been trying to get my project's tests working for components that use `<I18n />` and have not had any luck so far. When I checked the `react-i18next` repo to see if it had any tests for this, I couldn't find any so decided to write one. I might provide another PR with some more advanced tests as I start to debug my own project.
Thanks.

Add basic test for <I18n /> component

---

src/Trans.js
test/trans.render.spec.js
test/trans.spec.js

Use `i18n.t` in the Trans component if `t` is not set with props or present in the context.
This allows to use Trans with the I18nextProvider.
Fixes #352

Use t from I18n if not present in context

---

src/translate.js

For #369. It was slightly more complicated than just adding `if (typeof namespaces === 'function')             namespaces = namespaces(props);`, because when multiple of the same component were rendered, only the first one would run the function, then the closure in the HOC would have that result set to `namespaces` for every other.
I'm not certain if `Translate.namespaces` was being used elsewhere, but now that value can also be a function. If that'll cause issues, let me know and I'll try to implement it another way.

Allow translate HOC to take a function

---

src/I18n.js
src/context.js
src/translate.js
test/translate.render.wait.spec.js

Only would need to document the new option - if `waiting` is set to true, and we are not rendering `null`, we pass a `ready` flag to the children of `I18next`. If we're using the HoC, then in order to prevent naming clashes, rename `ready` as `tReady` and pass it as a prop to the `WrappedComponent`

Add renderNullWhileWaiting option

---

src/I18n.js

In <=IE10, `this.props` is null, so when attempting to set the namespaces,
the reference to `this.props.ns` raises an exception. By updating the
reference to use the version passed into the constructor, we are
consistent with other usages of props on the constructor, and I've
confirmed this patch works in <=IE10 as well.

Fix reference to props in constructor

---

src/Trans.js

Currently if you pass something different than ReactNode to `parent` prop, `propTypes` validation throws an error:
```
Warning: Failed prop type: Invalid prop `parent` supplied to `Trans`, expected a ReactNode.
```
This would happen if  you use `glamorousComponent` for example.
```js
// RenderedComponent.js
<Trans
i18nkey='common.myTransKey'
parent={Text}
dynamicVal={dynamicVal}
>
My <strong>interpolation</strong> and this is my <i>{{dynamicVal}}</i>
</Trans>
// Text.js
export const Text = glamorous.p({
fontSize: 16,
marginTop: 10
})
```

Allow to pass a function as parent for <Trans /> component

---

src/Trans.js
test/trans.spec.js

Since it can be passed in as a prop, we shouldn't require it to be present in context.
Fixes #473.

Don't require `i18n` in context

---

src/loadNamespaces.js

Patching `Object.entries` affects other code beyond this library, which
ideally should not happen. With this patch the polyfill is still used
when necessary but the global environment is not unexpectedly changed by
including react-i18next :)

Don't polyfill Object.entries globally

---

src/I18nextProvider.js
src/translate.js
test/i18nextProvider.spec.js
test/translate.spec.js

This allows the default namespace to be specified as a prop of
`I18nextProvider`. Previously namespace came from i18n instance option,
and then from arguments to the `translate` HOC. This allows the
`translate` HOC to be invoked without an explicit namespace, and the
parent `I18nextProvider` can define an alternate default namespace. This
allows sharing `translate`d components without hard coding a defaultNS
at build time and without cloning multiple i18n instances to set
alternate namespaces.
e.g.
```
const Translated = translate()(Elem);
<I18nextProvider defaultNS="namespaceOne">
<Translated />
</I18nextProvider>
<I18nextProvider defaultNS="namespaceTwo">
<Translated />
</I18nextProvider>
```

Support defaultNS from I18nextProvider props

---

src/Trans.js
test/i18n.js
test/trans.render.spec.js

Fixed the bug, with empty html tags in source for Trans component. 
Translators can (yes, they can) add some html tag into translations.
For example we had source 
```js
{
"key" : "Some text <1>other text<1>"
}
```
But translations manager decide to add some tags in translations:
`"Some text <br /> <1>other text<1>"`
After that react-i18next throw the error
```
TypeError: Cannot read property 'content' of undefined
at src/Trans.js:78:86
at Array.reduce (<anonymous>)
```

Skipped custom html tags

---

README.md

To prevent ugly red squares in code examples, the used language for syntaxe highlight should be changed

Use JSX syntaxe hightlight in README file

---

src/translate.js
test/translate.spec.js

I also chose to report `undefined` when no namespace is used with `translate()` and no default namespace is defined in options.

related to issue #504: also report default Namespace with translate()

---

README.md

The links in the README for react native are 404ing. This fixes it.

Correct URLs to reactnative-expo examples

---

index.d.ts
package.json

_For future releases, feel free to ping me to get the typings updated_
Resolves: #550 
This PR adds the typescript type definitions.
hoc usage
```javascript
interface Props extends WithNamespaces {}
export default withNamespaces()<Props>(AddressField);
```

Added Type Definitions

---

index.d.ts
package.json

Closes: #565 #563 #562 #568 #571 
- Fixed namespace type def and for when a extractor function is provided
- Removed unneeded default imports
- Improved types for hoc's

Improve typings for HOC's and fix imports

---

example/nextjs/pages/_app.js

This fixes the nextjs example page 3 which currently only shows default language during ssr.
Fixes https://github.com/i18next/react-i18next/issues/574

nextjs example page3 ssr rendering fix

---

src/NamespacesConsumer.js

Add a warning that is triggered if the new v13 of i18next is used without being aware of the [breaking changes](https://github.com/i18next/i18next/blob/master/CHANGELOG.md#1300).
This should offer a faster feedback loop.

Warn if i18next instance is a promise

---

package.json
src/index.d.ts
test/typescript/NamespacesConsumer.test.tsx
test/typescript/examples-react.test.tsx
tsconfig.json
tslint.json

- Add typescript usage tests for sanity and hook into ci to assist in keeping up to date.
- Fix several errors in the type definition
Closes #654

Add typescript tests with example usage as sanity check and hook into `test`script

---

example/reactnative-expo/App.js
example/reactnative-expo/app.json
example/reactnative-expo/package.json

This is the PR to respond the ver up of Expo 32.
Now react-navigation v3 is available then I needed to use `createAppContainer ` with `WrappedStack`.

Update the example to respond Expo 32.0.0

---

hooks.d.ts

Add some missing typings from latest hooks variant change and also some improvements
- Make some `Trans` props optional
- Add second argument to `useTranslation`
- Sync with prettier
Might also want to use i18next/i18next#1163 like #665 does for `t` in `useTranslation` return, but I leave it as it is right now

hooks variant Trans props and useTranslation typings

---

package.json
src/index.d.ts
test/typescript/NamespacesConsumer.test.tsx

Closes #693 - optional props
Closes #695 - parameterized return type usage
Depends on:
https://github.com/i18next/i18next/pull/1188

TFunction usage inside NamespacesConsumer should behave

---

hooks.d.ts

This update useTranslation hook return type to use `TFunction`

fix: useTranslation hooks typing

---

src/index.d.ts

The reportNS prop of I18nextProvider is missing in I18nextProviderProps.
https://github.com/i18next/react-i18next/blob/5e929b56709d92c1bce87cb939bb00800ebfafb0/src/I18nextProvider.js#L14
It was added in PR https://github.com/i18next/react-i18next/pull/500

Add TS definition for reportNS prop

---

src/index.d.ts
test/typescript/examples.test.tsx

Update typescript tests for hooks and fix an error in the example

---

src/index.d.ts
test/typescript/I18nextProvider.test.tsx

Add missing I18nextProvider interface to typings

---

example/react/src/App.js
src/index.d.ts
src/useTranslation.js
test/typescript/examples.test.tsx
test/typescript/useTranslation.test.tsx
test/useTranslation.spec.js

Added possibility to use useTranlation not only expecting an array but also an object. Should help #712

Added possibility to use useTranlation returning Array or Object

---

src/index.d.ts
test/typescript/examples.test.tsx

Fixes https://github.com/i18next/react-i18next/issues/727

Make children optional within TransProps

---

src/useTranslation.js
test/useTranslation.loading.spec.js

This new option `useSuspense` on the hook should help migration from 9.x to 10.x and progressive integration of Suspense

Allow to enable/disable useSuspense at a hook or component level.

---

package.json
src/index.d.ts
test/typescript/examples.test.tsx

Adds missing type definitions for the `ready` return value of the `useTranslation` hook and the `tReady` prop added by the `withTranslation` HOC, fixes #751.

Add ready/tReady type definitions

---

src/utils.js

Resolves #773 
The bug was due to sending `null` as the context to `console.warn.apply`.
Fixed by passing `console` as the context.

Resolve #773 by sending console as the first argument to apply

---

README.md

**Describe the issue**
Found out the dependencies version used in Codesandbox example at README.md to be quite outdated and not supporting the latest version (including react-i18next and i18next) while learning and playing around. 
`import { translation } from 'react-i18next'` were changed to `withTranslation`. 
Took me some time to find the cause while updating one of ours company production app. Hope this help.
**Screenshots**
Instead of screenshot here is the link to current example
[Current Codesandbox example](https://codesandbox.io/s/8n252n822)
[Update Codesandbox example](https://codesandbox.io/s/14m4o720mq)

Update Codesandbox example

---

src/Trans.js
test/i18n.js
test/trans.render.spec.js

Hi,
Please consider my PR for improve functionality of react-i18next.
- added support for nested components, like dynamic lists just on place in Trans component
For now to include, for example, `<ul>` with several `<li>` we need to create  additional Component and it makes supporting of code much more complicated (several components within one file... looks like hell ).
So with this PR now Trans works like this
`<Trans i18nKey="key" components={[<ul>{['one', 'two'].map((item) => <li>{item}</li>}</ul>]} >`
- added support for values from translation message.
Another issue that really annoying me that for components we need to provide some value.
for now:
<Trans i18nKey="test" values={{v: 'some value'}} components={[`<span>{''}</span>`]} />
I propose additional format:
<Trans i18nKey="test" …

Adding support for nested component inside Trans

---

README.md

In the `Requirements` part of the README, `react-dom` was not present. But with version 10 of i18next using React Hooks, you have to have`react-dom >= 16.8.0` otherwise it will throw an error like the following: 
```
Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)
```
Anyway thanks for your great job 👍

Add in the requirements part of README: react-dom. 

---

src/utils.js
src/withSSR.js
src/withTranslation.js

Updating the HOC components to have displayNames consistent with the react docs definition: https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging
This affects some dev tools like react-cosmos that use this format to detect what the "Original" component name is. Also standard is good.

Fix the displayName of HOC components

---

src/withTranslation.js
test/withTranslation.spec.js

use forward for withTranslation

use forwardRef for withTranslation

---

src/useTranslation.js

The warning message is outdated. Plugin name is updated.

update i18next plugin name

---

src/index.d.ts
src/index.js

Linked to #823, it could be useful for users to have access to the i18next instance in context.

export I18nextContext to allow users to get the context instance of i18next

---

src/useTranslation.js

The second params of useEffect should be `[]`, otherwise it will be called when re-render every time.

Fix useEffect mount/unmount usage

---

src/withSSR.js
src/withTranslation.js
test/withSSR.spec.js
test/withTranslation.spec.js

Hi, this PR will add a public static property `WrappedComponent` (tests included) to access original component.
It looks like a *de facto* standard in *higher order components*, at least that's what `react-router` and `react-redux` do, so I expected any higher order component to do the same. This allows to access original component in a standardized way and access its original static properties (in my case, a `loadData` property used for server-side data fetching, but that could be anything else). Without this property, I can't use your HOC with mine as it "breaks the chain". This PR includes implementation and test :+1:
Thanks for your work!
Note: this is quite the same PR which was merged last week in dunglas/react-esi#6

HOC: expose wrapped component as WrappedComponent property

---

src/I18nextProvider.js
src/useTranslation.js
test/useTranslation.spec.js

During react-i18next evolved the support (introduced at i18next/react-i18next#478) of `defaultNS` prop has been dropped from I18nextProvider. So attempting to restore it.
We're still looking forward to share same instance of i18next between different provider instances and hooks.
```javascript
const i18n = /* some i18next instantiating */
const Translated = () => {
const {t} = useTranslation();
return (<div>{t('the_key')}</div>);
};
const FirstWrapper = () => (
<I18nextProvider i18n={i18n} defaultNS="firstOne">
<Translated />
</I18nextProvider>
);
const SecondWrapper = () => (
<I18nextProvider i18n={i18n} defaultNS="secondOne">
<Translated />
</I18nextProvider>
);
```

Restore support passing the defaultNS as I18nextProvider prop 

---

src/useTranslation.js

When dynamically changing the `namespaces` passed to `useTranslation()` over time, they are now reloaded and trigger a re-render. This reimplements the behavior first introduced in #523 as it was likely broken in the release of the new hooks-based API.
See https://github.com/i18next/react-i18next/issues/817#issuecomment-503650139 and #520 for context.

Reload translations whenever namespaces passed to useTranslation() change

---

package.json
src/index.d.ts
test/typescript/I18nextProvider.test.tsx

Depends on https://github.com/i18next/i18next/pull/1296

fix types for use()

---

src/useTranslation.js

In the `useTranslation` hook, `useContext` is called conditionally, which breaks the Rule of Hooks, so it may cause problems in the future. This fixes it by calling `useContext` on every render, just not always using the result from it.

Fix hooks being called conditionally in useTranslation

---

src/index.d.ts
test/typescript/context.test.tsx

I'm working with SSR and stumbled across this issue and need access to only the used namespaces: https://github.com/i18next/react-i18next/issues/711.
As it appears, the suggestion is to use `i18next.reportNamespaces.getUsedNamespaces()`?
However, the types do not currently reflect that. 
```typescript
import * as i18next from 'i18next';
i18next.reportNamespaces.addUsedNamespaces(['translation']);
//      ^^^^^^^^^^^^^^^^
// Property 'reportNamespaces' does not exist on type 'i18n'
i18next.reportNamespaces.getUsedNamespaces();
//      ^^^^^^^^^^^^^^^^
// Property 'reportNamespaces' does not exist on type 'i18n'
```
```typescript
import * as i18next from 'i18next';
i18next.reportNamespaces.addUsedNamespaces(['translation']); // valid
i18next.reportNamespaces.getUsedNamespaces(); // valid, …
```

Update types for reportNamespaces

---

src/index.d.ts
test/typescript/withSSR.test.tsx

Currently, there are few issues with the `withSSR` type definitions:
1. Function components aren't valid
1. Any component (class or function) with props were invalid
1. No type-safety around `initialI18nStore` and `initialLanguage`
```typescript
const FunctionComponent = () => {
return null;
};
const ExtendedFn = withSSR()(FunctionComponent);
//                           ^^^^^^^^^^^^^^^^^
// Type '() => null' provides no match for the signature 'new (props: {}, context?: any): Component<{}, any, any>'
<ExtendedFn initialLanguage={'en'} initialI18nStore={{ en: { namespace: { key: 'value' } } }} />;
```
This is because the type definition for `WrappedComponent` is `React.ComponentClass` which doesn't include `React.FunctionComponent`. This can be solved with the `React.ComponentType`. …

Improve withSSR type definition

---

src/Trans.js

If a `count` is specified in the `values` object passed to Trans, we should use it, even if the `count` property is not provided.
https://github.com/i18next/i18next/issues/1330
By changing the order of the construction of `combinedTOpts`, this should ensure that the behaviour is as expected.

Use count from `values` object passed to Trans

---

src/index.d.ts
test/typescript/Trans.test.tsx

It seems `t` function is currently missing from types, let's add it back

Add t function to TransProps types

---

rollup.config.js

Rollup doesn't set targets for browsers.
This commit addresses: https://github.com/i18next/react-i18next/issues/915
My question: is this an appropriate solution? My knowledge of the various JS module types isn't up to the point where I can say definitively one way or the other.

Update `rollup.config.js` for IE11 Transpilations

---

src/withTranslation.js

When wrapping components with only the withTranslation HOC, this code works well:
```js
export const Input =  withTranslation('translation', { withRef: true })(Input),
```
But when using multiple ones, `withTranslation` was not propagating `forwardedRef` to its children, making code like this break (it also used to work in previous versions):
```js
const InputWithRef = compose(
withTranslation(),
withSomeOtherHOC(),
withProps(({ forwardedRef }) => ({ ref: forwardedRef }))
)(Input);
export const Input = React.forwardRef(
(props, ref) => <InputWithRef {...props} forwardedRef={ref} />
);
```
Fixes #990

Fix withTranslation eating up forwardedRef prop

---

src/withTranslation.js

fix for withTranslation.js: Unexpected token (28:39)

---

src/withTranslation.js

`forwardedRef` was always passed down to its children in #992, but as pointed in the comments, it should only be passed down if `options.withRef` is false (if it is true, we want to pass the ref as `ref` and remove `forwardedRef` from props) and if `forwardedRef` is defined.

Only pass forwardedRef to children if options.withRef is false

---

src/useSSR.js

If a the store is initialized with data from Server side rendering, it fire these warnings anyway:
`i18next was not initialized... This means something IS WRONG in your application setup.`
However, the application setup is fine, the warning is inconsistent.
I think this PR will do the trick: i18n should be considered as initialize once it receive initialI18nStore datas.

Store should be initialized after useSSR

---

src/useTranslation.js
test/useTranslation.spec.js

t accepts an array of keys and will use first resolved key or fallback to the last key https://www.i18next.com/overview/api#t
But when i18next instance is not ready useTranslation hook simply returns an identity function, t(['doh', 'Human friendly fallback']) gives me ['doh', 'Human friendly fallback'] instead of 'Human friendly fallback'

fixed graceful fallback for keys

---

src/index.d.ts
test/typescript/Trans.test.tsx

I've also allowed `null` as this is the cleanest way I use to override the default parent:
* `undefined` -> use default parent from settings
* `string | React.ComponentType<any>` -> use in `React.createElement`
* `null` -> do not add a parent

Allow ComponentType for Trans' `parent` type.

---

README.md

I think the actual warning doesn't make sense anymore since the current versions of react-native support hooks ;) ! However, the warning is still usefull to keep in mind that you need 0.59 or higher :)

:memo: Update warning about react-native

---

src/index.d.ts
test/typescript/Translation.test.tsx
test/typescript/useTranslation.test.tsx
test/typescript/withTranslation.test.tsx

Added a typing and some tests that appear to have been missed in a [previous feature](https://github.com/i18next/react-i18next/commit/a46263ed3f5bd4c84cb4353cbdcf2f1c34c79214).
- **Translation**: added typing for the _ready_ parameter and added a test to validate it.
- **useTranslation**: updated TypeScript tests to validate _ready_ return value
- **withTranslation**: updated TypeScript tests to validate _tReady_ prop (WithTranslation).

Translation component's ready parameter is missing in TypeScript definition

---

src/index.d.ts
test/typescript/I18nextProvider.test.tsx

Add optional defaultNS

---

src/useTranslation.js

Once the translations are loaded from backend, the hook sets its `t` function without checking that the component is still mounted, which induces an error from `react-dom`.
```Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.```
I've updated the code to keep the `isMounted` pattern to be consistent with the previous version, but I'll gladly change it for a promise cancellation if you find it more appropriate.

[useTranslation] Avoid setting the new `t` function if the component is unmounted.

---

package.json

Noticed that all the exports were being included output bundles even though only a few were used.
This pr adds `sideEffects: false` to the `package.json` so that bundlers like webpack can tree shaking unused code. 
BEFORE:
AFTER:

Add sideEffects false to package json to allow tree shaking

---

src/I18nextProvider.js
src/Trans.js
src/context.js
src/useSSR.js
src/useTranslation.js
test/useTranslation.spec.js

There is no need for `getHasUsedI18nextProvider`
If `I18nContext.Provider` was used then `useContext(I18nContext`) will return a value.
In cases when user overrided `I18nContext.Provider` value we fallback to an empty object `useContext(I18nContext) || {}`

refactor(context): remove redundant check `hasUsedI18nextProvider`

---

package.json
src/Trans.js
test/i18n.js
test/trans.render.spec.js

Dear maintainers of react-i18next,
Below is my pull request for #1117 where I initially requested the option to have props within a `<0 ...props></0>` passed to its final component. It is a very simple fix. 
I have tried running `npm run test` but it seems the distribution lacks `dtslint/dtslint.json` - I have tested the code extensively and don't see any issues that may occur. 
I also wasn't sure where to change the documentation. If you point me in the right direction I will adapt where necessary.

Added lodash and merge option in mapAST

---

icu.macro.js

We've been using icu.macro just fine at our organization for a while now. 
Very recently, we started implementing typescript support for our org, and this brought to light a little issue with the macro. 
```FAIL packages/locale/src/PluralsAndGenders.test.js
● Test suite failed to run
/Users/joeycozza/fs/zion/packages/locale/src/PluralsAndGenders.stories.js: react-i18next/icu.macro: [BABEL] unknown: Preset /* your preset */ requires a filename to be set when babel is called directly,
```
babel.transform(code, { filename: 'file.ts', presets: [/* your preset */] });
```
See https://babeljs.io/docs/en/options#filename for more information. Learn more: https://www.npmjs.com/package/react-i18next
at validateIfOptionNeedsFilename (node_modules/@babel/core/lib/config/full.js:274:11)
at …
```

providing filename when running babel.parse in icu.macro

---

src/Trans.js
src/index.d.ts
test/trans.render.object.spec.js
test/typescript/Trans.test.tsx

This PR intends to close #1136. It provides:
1. More versatility to the Trans component as now is possible to interpolate self-closing tags
2. Updated Trans typing, reflecting the alternative usage described in [docs](https://react.i18next.com/latest/trans-component#alternative-usage-v-11-6-0).
3. Improved readability on `mapAst`'s reducer.
The third point is opinionated, but I was having trouble to reason with it the way it was written. 
I was also forced to write the `pushTranslatedJSX` function (still unsure if this is the best name though) to keep the DRY principle.

feat: Trans interpolating self-closing tags in components prop(object)

---

src/index.d.ts
test/typescript/useSSR.test.tsx

This PR updates the type definitions for the `useSSR` function, to closely match the `withSSR` definitions.

Update types for useSSR

---

src/index.d.ts
test/typescript/context.test.tsx

Wrap I18nContext value in an object
FIX: https://github.com/isaachinman/next-i18next/pull/799
FIX: https://github.com/isaachinman/next-i18next/issues/789

fix: typescript definition of context object

---

src/useTranslation.js

As documented in [my comment about issue #1124](https://github.com/i18next/react-i18next/issues/1124#issuecomment-680153621), this fix should avoid `setState` while react is rendering.
See #1124 for more details.
-  ~tests are included~
-  ~documentation is changed or added~

Avoid setState while react is rendering

---

src/I18nextProvider.js
test/I18nextProvider.spec.js

Context value should be memoized to avoid re-rendering in consumer components.
Actually, when I18nProvider is re-rendered event if props are not changed, value object is recreated and all consumer components are re-rendered.

Avoid redundant re-rendering

---

src/Trans.js
test/trans.render.spec.js

feat(trans): allow interpolation in tOptions if provided

---

src/Trans.js
test/trans.render.spec.js

related to: https://github.com/i18next/react-i18next/issues/1205

trans should work with misleading overloaded empty elements in components

---

.prettierignore
package.json
src/ts4.1/index.d.ts

With Typescript 4.1, now it is possible to use recursive conditional type and template literal string. This PR aims to make the `t` function fully typed and supporting single and multiple namespaces. It works with `useTranslation (hooks)`, `withTranslation (HoC)`, `Trans Component` and `Translation (render prop)`.
You just have to rely on type augmentation technique to override the default Resources with the resource language object.
**For example:**
```ts
// src/i18n/config.ts
export const resourcesEN = {
earnings: {
header: {
title: 'Earnings',
subTitle: 'See your Earnings'
},
notes: 'Balance'
}
};
i18n.use(initReactI18next).init({
resources: {
en: resourcesEN,
},
});
```
Type augmentation
```ts
// @types/react-i18next/index.d.ts
import "react-i18next";
import resourcesEN from …
```

Make the translation function fully type-safe

---

src/index.d.ts
src/ts4.1/index.d.ts
test/typescript/Trans.test.tsx

Typescript bug fix: the `components` prop of `Trans` does not need to be mutable as it won't be modified. I'm changing the types to reflect that. Note that it was already done previously for Typescript <4.1 for arrays.

Accept const components prop for Trans.

---

src/ts4.1/index.d.ts

Workaround for #1222
In this [link](https://www.typescriptlang.org/play?noUnusedLocals=true&ts=4.1.2#code/C4TwDgpgBAYghgGwQIzgYwNYB4YBooAqUAvFBhCAPYBmUAShAM6UCuATmkwHwlQDaBALpQIAD2AQAdgBNG-SRABuENsID8sKAC5CAbgBQ+gPRGoAOUpsAtogCWAL2iNbkgOYJokuFaZh0EfVBIKAB5K1tgAEE2NjgQAAU2SjBGLAIeUgBRUTQEFmkINPxyKlo4SRA+QS4DIOhIsEgZAGkKVOaARnxmgCYMqAADABIAb06oADIoRmA2F1cAXwA6UbCI6NiEpJSsXp4pmbm3BYHa8GgLaztHHqKoZt4SmkJ+h7EJGTkn2gJ9KCgNAQ+M1hO8pLJ6BA0JZpFhDvN8OUQFw-gCoA0mtJWiB2sUKM8gSCeAAfdGNcHY3HmSw2BAOCC3QnVFH-HQKZRsVFspQqM7BS60+lpfrfQhQUkC64M4UGYymSV0xxQKwsBDAWxgDxQLw+Rh+TiMQLnKAAVUktkokgIlAAkpIJGxGFD1ZasCb+gAKE0icTguRI1EaD0YHQmgCUJB4ikotmkXO1PLYEbBnygwZ0LmoKigNojxCjMbj-w0Nvj7N5RuCABk4DMQtRhbwzRarbb7SonWgXZIsKiiCmIUi0R68zwiNyOfoeAO5CPI1BM9m6IH6GXE3z6uSZGYAMpYMzdfrDEZmSbTWbzBZaUYPA4X46nSsXGlSgCyqvVd29M7I+J+ …

Add workaround to suppress infinite instantiation warning

---

src/index.d.ts
src/ts4.1/index.d.ts
test/typescript/withTranslation.test.tsx

I experienced TS errors when I tried to define props interface for a component that was wrapped in `withTranslation()` and had `defaultProps`. 
```
interface IStepperProps extends WithTranslation {  
isHeadless: boolean; 
defaultStep: number;  
isStepInvalid?: boolean;
submitStep?: () => void;
}
class Stepper extends React.Component<IStepperProps, IStepperState> {
static defaultProps: Partial<IStepperProps> = {
isHeadless: true,
defaultStep: 1,
};
(...)
} 
export default connect(mapStateToProps)(withTranslation()(Stepper));
```
The `isHeadless` and `defaultStep` props have been marked in the interface as non-optional because they were needed and always provided in `defaultProps`. But TypeScript complained if I didn't pass them in JSX for the component:
```
<Stepper>…</Stepper>
TS2739: …
```

withTranslation() typing fix for defaultProps

---

example/react-typescript4.1/namespaces/package.json
example/react-typescript4.1/namespaces/yarn.lock
example/react-typescript4.1/no-namespaces/package.json
example/react-typescript4.1/no-namespaces/yarn.lock

- n/a tests are included
- n/a documentation is changed or added
1. Check out the repo
2. Go to `example/react-typescript4.1/namespaces/` (and `no-namespaces`)
3. `yarn install`
4. `yarn start`
I updated the types to the version matching `react` dependency and it compiles properly now.

Fix compilation error in typescript examples

---

src/index.d.ts
src/ts4.1/index.d.ts

#778 had forgotten the HOC
If you wish, I can also update:

Updated TS definitions

---

src/useTranslation.js
test/useTranslation.spec.js

-- Prettier seems to be run on committed files as part of the pre-commit husky hook and did some little code changes in useTranslation.js, not my fault ;-)
-- No need for documentation update

Fix allow to replace i18n in provider with useTranslation hook (#1272)

---

src/useTranslation.js

Minor optimizations
Works by switching to `useState(() => initialValue)` and `setState((prevState) => nextState)`

refactor: remove unneeded object

---

ts4.1/icu.d.ts
ts4.1/icu.macro.d.ts

fix #1299: add support for icu macro in typescript

---

src/Trans.js
src/context.js
test/trans.render.spec.js

The `transWrapTextNodes` option instructs react-i18next to wrap text nodes in a user-specified element. By default, text nodes are not wrapped.
Fixes: https://github.com/i18next/react-i18next/issues/1323

Add `transWrapTextNodes` option

---

package-lock.json
package.json
test/typescript/custom-types/Trans.test.tsx
test/typescript/custom-types/Translation.test.tsx
test/typescript/custom-types/custom-types.d.ts
test/typescript/custom-types/tsconfig.json
test/typescript/custom-types/useTranslation.test.tsx
test/typescript/withTranslation.test.tsx
ts4.1/index.d.ts
tsconfig.json

This PR allows the declaration of custom `defaultNS` types and should fix #1302 
It also implements a new way of typing the `Resources` by using the `resources` key inside `CustomTypeOptions` instead of the previous API, `Resources` has been marked as deprecated as well
```ts
// i18n.ts
i18n.use(initReactI18next).init({
defaultNS: 'ns1'
...
});
// react-i18next.d.ts
declare module 'react-i18next' {
interface CustomTypeOptions {
defaultNS: 'ns1';
resources: {
ns1: typeof ns1;
ns2: typeof ns2;
};
}
}
```

Allow for Custom DefaultNS typing

---

test/typescript/custom-types/useTranslation.test.tsx
ts4.1/index.d.ts

`useTranslation()` typings signature changed to allow a readonly version of namespaces argument... 
```typescript
// From a readonly configuration. the const here is used
//  - to guarantee immutability (type level)
//  - helps typescript to narrow the type
//
export const nsConfig = ['ns1', 'ns2'] as const; 
// An example component
export const Test: React.FC = () => {
const { t } = useTranslation(nsConfig);
return <></>
}
```
Prior to this P/R, typecheck in strict mode would complain about
```
TS2345: Argument of type 'readonly ["common", "demo"]' is not assignable to parameter of type 'Namespace<"common" | "demo" | "home"> | undefined'.   The type 'readonly ["common", "demo"]' is 'readonly' and cannot be assigned to the mutable type '("common" | "demo" | "home")[]'.
```
It's possible …

feat(types): allow readonly namespaces in useTranslation

---

ts4.1/index.d.ts

Follow up of 
- feat(types): allow readonly namespaces in useTranslation, see https://github.com/i18next/react-i18next/pull/1339
While the initial P/R allows to readonly namespace array... the `t` function choose to fallback to all configured namespaces (ie: 'common', 'home', 'other-context')... defeating perfect typechecks
```tsx
export const nsPageConfig = ['common', 'home'] as const; 
export const Page = () => {
// 1. Ok it works thx https://github.com/i18next/react-i18next/pull/1339
const { t } = useTranslation(nsPageConfig);
return (
<div>
// 2. Ok it works, the typecheck occurs 
<span>{t('home:thekeyexists')}</span>
// 3. Oups, it allows 'other-context', but it's not in the nsPageconfig
<span>{t('other-context:thekeyexists')}</span>
</div>
);
}
```
With this P/R it will work well. …

feat(typings): support readonly namespaces in TFuncKey

---

src/Trans.js
test/trans.render.spec.js

This avoids problems with user given values potentially breaking the parse tree
Regarding https://github.com/i18next/react-i18next/issues/1344

parse first, then interpolate

---

test/typescript/returnTypes.test.ts
ts4.1/index.d.ts

Working with react-i18next and typescript, I found that **returnNull** and **returnEptyString** [options](https://www.i18next.com/overview/configuration-options#translation-defaults) were not represented in typescript signatures.
By providing keys for these values inside the `CustomTypeOptions`, we can refine the return types for TFunction. 
```tsx
const dictionary = {
...
nullValue: null,
emptyString: "",
}
t('nullValue') // By default, signature returns null.
t('emptyString') // By default, signature returns ""
```
```tsx
declare module 'react-i18next' {
interface CustomTypeOptions extends MyCustomTypeOptions {
returnNull: false,
returnEmptyString: false,
}
}
t('nullValue') // After moduleAugmentation, signature returns string, representing the key.
t('emptyString') // After …
```

feat(types): add returnNull and returnEptyString options to TypeOptions interface

---

src/Trans.js
test/trans.render.spec.js

I stumbled upon a bug when integrating `react-i18next` in an app that uses preact. It turns out that if you use `Trans` component with no `children` and you do not pass any `components`, the whole translation will not render. It works with React, but not with Preact. Here are simple reproductions:
- React: https://codesandbox.io/s/react-3txsi
- Preact (no `children` and no `components`): https://codesandbox.io/s/preact-trans-no-children-no-components-unwxw
- Preact (no `children`, empty object passed to `components`): https://codesandbox.io/s/preact-trans-no-children-empty-object-components-wnrmq

Fix preact issue with Trans when both children and components are undefined

---

index.d.ts
package-lock.json
package.json
src/useTranslation.js
test/useTranslation.spec.js
ts4.1/index.d.ts

Add `keyPrefix` option for `useTranslation` hook (Issue #1359)
```
i18next.addResource('en', 'translation', 'very.deeply.nested.key', 'here!');
const { t } = useTranslation('translation', { i18n: i18next, keyPrefix: 'very.deeply.nested' });
const text = t('key'); // "here"
```
- Added `keyPrefix` param handling for `useTranslation` hook
- Added test for checking the param
- Added TS typing
- Updated `i18next` dep to `2.6.0` (`keyPrefix` param added to `getFixedT`)

feature: add key prefix support to useTranslation hook

---

ts4.1/index.d.ts

Closes https://github.com/i18next/react-i18next/issues/1394

Remove generics from Trans component to suppress warning issue

---

test/typescript/custom-types/Trans.test.tsx
test/typescript/custom-types/custom-types.d.ts
test/typescript/custom-types/useTranslation.test.tsx
test/typescript/returnTypes.test.ts
ts4.1/index.d.ts

Closes https://github.com/i18next/react-i18next/issues/1387

Add type-safe support to deep keyPrefix

---

package.json
ts4.1/index.d.ts

Closes https://github.com/i18next/react-i18next/issues/1407
Before: 
After:

Remove `undefined` from conditional type

---

package-lock.json
package.json
ts4.1/index.d.ts

Fixes #1434

---

test/__snapshots__/icu.macro.spec.js.snap
test/icu.macro.spec.js
ts4.1/icu.macro.d.ts

Fixes #1444 
- [ x] only relevant code is changed (make a diff before you submit the PR)
- [ x] run tests `npm run test`
- [x ] tests are included

Fixes #1444 - add values field to Plural component in macros

---

package.json
ts4.1/index.d.ts

Closes https://github.com/i18next/react-i18next/issues/1459 and bump ts version

Fix error for typescript 4.6

---

ts4.1/index.d.ts

Closes https://github.com/i18next/react-i18next/issues/1467

Add nsSeparator to CustomTypeOptions

---

icu.macro.js
test/__snapshots__/icu.macro.spec.js.snap
test/icu.macro.spec.js

I noticed that the Trans macro generates invalid code when children contains a double quote. From [ast explorer](https://astexplorer.net/#/gist/642aebbb9e449e959f4ad8907b4adf3a/4a65742e2a3e926eb55eaa3d657d1472b9ac7970):
```jsx
// before
<Trans>"</Trans>;
// after
<Trans defaults="\"" components={[]} values={{}} />;
```
According to the [JSX spec](https://facebook.github.io/jsx/#prod-JSXAttributeValue) this isn't valid; JSX doesn't support any kind of escaping inside of `"` quoted attributes. Babel, tsc, prettier, etc all fail when parsing. To get around this we can just wrap the value in brackets. I made it only happen when the string in question contains a quote.
```diff
// before
<Trans>"</Trans>;
// after
- <Trans defaults="\"" components={[]} values={{}} />;
+ <Trans defaults={"\""} …
```

Update macro to wrap defaults in brackets when necessary

---

index.d.ts
ts4.1/index.d.ts

Fixes #1477 by explicitly specifying `children` prop on `I18nextProviderProps`.

Add explicit `children` prop to `I18nextProviderProps`

---

ts4.1/index.d.ts

Fixes #1476 by add `ReactNode` to the `TDefaultResult` type

Fix type 'TFunctionResult' is not assignable to type 'ReactNode' on React 18

---

ts4.1/index.d.ts

ReactNode was incorrectly added in the #1480 without React prefix - breaks tsc compilation, unless skipLibCheck is set.

ReactNode should be prefixed with React

---

ts4.1/index.d.ts

Disable no-null-undefined-union rule for TFunctionResult imported from i18next.

Disable no-null-undefined-union for TFunctionResult

---

package-lock.json
package.json
ts4.1/index.d.ts
tslint.json

Fixes #1483.
Allows objects to be passed to Trans component with @types/react@18.

Added objects explicitly to Trans children

---

README.md

The url of the "serverside" link was pointing to https://www.i18next.com/supported-frameworks.html instead of https://www.i18next.com/overview/supported-frameworks
- [x ] only relevant code is changed (make a diff before you submit the PR)
- [x ] run tests `npm run test`
- [x ] tests are included
- [x ] only relevant documentation part is changed (make a diff before you submit the PR)
- [x ] motivation/reason is provided

Fixed the link pointing to supported frameworks

---

ts4.1/index.d.ts

Closes https://github.com/i18next/react-i18next/issues/1490 and https://github.com/i18next/react-i18next/issues/1483

Fix Trans component to support react 18 types

---

ts4.1/index.d.ts

Closes https://github.com/i18next/react-i18next/issues/1498

Fix missing generic type for HTMLAttributes

---

ts4.1/index.d.ts

closes https://github.com/i18next/react-i18next/issues/1508

fix Translation component types

---

ts4.1/index.d.ts

Fixes the error that typescript started raising since last release 11.16.10:
```
Error: [...]react-i18next/ts4.1/index.d.ts(371,75): error TS2706: Required type parameters may not follow optional type parameters.
```

fix Translation component types regression

---

index.d.ts
package.json
test/trans.render.object.spec.js
test/typescript/Trans.test.tsx
ts4.1/index.d.ts

Since the values in the components prop are being passed to cloneElement only the ReactElement type is really supported. All other types accepted by ReactNode will cause a runtime error. You can test this by checking out the first two commits in this branch.
- d8904f768ae5aad951197e736e62152e460101fd: Types pass but as the unit test shows react throws
- 563966bcab519ca6ac26fd9d930bda0275cc7519: Corrected types: tslint now fails
- 516fbdc7ecbc6d1adfa653f902ec0b51b9dd3d7c & 9509d54ab799bbca59356b8acf96627f23441e75: I removed the example typescript error and tests for invalid behaviour

Stricter typescript type for Trans components prop

---

src/Trans.js
src/context.js
src/withSSR.js
src/withTranslation.js

For easier tree shaking (webpack, rollup, ...), actual used import for React could be explicit

style: explicit React imports

---

ts4.1/index.d.ts

This PR fixes TypeScript error which prevents multiple nodes to be used inside core React elements when `allowObjectInHTMLChildren` is set to true.
Code example that fails on the latest published version with React 18 but works correctly with this PR:
```tsx
<Trans t={t}>
View <b>{{ count }} cards</b>
</Trans>
```
Resolves #1506

allow iterable with objects as children

---

src/Trans.js

- `react-i18next` when used with the latest `preact` version throws a console warning related to accessing a deprecated property (see screenshot)
-  When [upgrading from preact 8.x](https://preactjs.com/guide/v10/upgrade-guide/#notes-for-library-authors) the `VNODE` structure in `preact` was changed from `children -> props.children`
-  when `getChildren` function in `src/Trans.js` tries to access `node.children` first, `preact` throws a deprecated API console warning
- one of the ways to fix this is to follow the same pattern we do in [`hasChildren` function](https://github.com/i18next/react-i18next/blob/master/src/Trans.js#L8) i.e try to access `node.props.children` first if `node.props` exists
- This PR includes that change

Fix console warning in preact due to  Trans accessing node.children first

---

src/unescape.js
test/unescape.spec.js

Adds support for unescaping the `/` character. This is one of the characters that i18next itself escapes so I think this is a must.
This fixes #1487 which is closed but not fixed.
Note I have only handled exactly `&#x2F`, case sensitively. This is what i18next's escaper produces so it's enough to fix the issue. Handling case insensitivity would be a further improvement, though this applies to some of the existing codes too. It's not completely trivial. For example, some entities support all-lowercase and all-uppercase versions but not mixtures, and some only support lowercase. For example, `&amp;` and `&AMP;` are both valid versions of the ampersand, but `&aMp;` is not. However for ellipsis, only `&hellip;` is supported, `&HELLIP;` is not. The numeric codes like `&#x2F` appear to support …

support unescaping forward slash

---

index.d.ts

Closes https://github.com/i18next/react-i18next/issues/1543

Fix react merged types

---

TransWithoutContext.d.ts

Closes https://github.com/i18next/react-i18next/issues/1601
Identifying the source of the problem was challenging, but thanks to a reproducible example shared by @sebastien-comeau, I was able to identify the root cause.
By default, when the `t` function is not passed, the inferred value for `KPrefix` should be `undefined`. However, due to a TypeScript limitation, the `KPrefix` was not maintaining its default signature of `undefined` and instead was inferring all keys from the `KeyPrefix`. This caused the `ParseKeys` function to map over the entire list of keys and key prefixes in order to filter out the keys that started with every `KPrefix` value. 
As a result, using the `Trans` component without specifying a `KPrefix` value could lead to an unnecessary exponential increase in the number …

Fix performance issue in `Trans` component

---

.eslintrc
index.d.ts
src/TransWithoutContext.js
test/trans.render.dynamic.spec.js

Hi! This PR closes #1658.
- Always return children as an array from getChildren (for isI18nDynamicList)
- This is the bugfix
- Reduce false positives when checking for nodes needing handling with empty children
- This is just something I noticed while working
- Remove React warnings in Trans component by removing i18nIsDynamicList prop while rendering
- Again, this is just something I noticed and thought to fix while I was at it

Fix non-list dynamic content in Trans component

---

src/TransWithoutContext.js
test/trans.render.dynamic.spec.js

Hi @adrai, this is followup to #1660. I noticed that rendering was still not working when using dynamic strings. This PR fixes that.

Render all children regardless of type when using i18nIsDynamicList prop

---

src/TransWithoutContext.js
test/i18n.js
test/trans.render.spec.js

Don't use `defaults` prop as default key

---

index.d.ts
package-lock.json
package.json
test/typescript/Trans.test.tsx
test/typescript/custom-types/Trans.test.tsx
test/typescript/custom-types/custom-types.d.ts

Fixes issues where interpolations alongside other HTML element children would trigger TypeScript errors. Added tests to make sure this stays working.
Note: I went with React 18 typings becuase React 16 typings allowed for objects to be passed as children, which made it hard to test that our `allowObjectInHTMLChildren` option was working correctly. This shouldn't affect end-users since it's a development dependency.

Allow iterable `ReactI18NextChildren` as children

---

index.d.ts

Fix missing TransWithoutContext type (#1671)

---

TransWithoutContext.d.ts
test/typescript/custom-types/Trans.test.tsx
test/typescript/custom-types/TransWithoutContext.test.tsx
test/typescript/custom-types/i18next.d.ts
test/typescript/misc/Trans.test.tsx
tsconfig.json

fixes #1730.
This is technically a breaking change since it change `Trans` and `TransProps` type parameters, however I don't think usually people explicit them when using the component... but who knows 🤷.
-----
I tried to replicate a type parameter structure similar to the `TFunction`, 
however, looks like that using a single `TOpt` type parameter doesn't pass the property values (like `context`) down to `TransProps` properly so `ParseKeys` is not aware of the context value.
The only alternative is to add a new type parameter and pass it down the chain, which is basically what @stefan-schweiger proposed in the above linked issue (Thanks 🙏). 
----

types(Trans): add typechecking on `context` prop

---

src/context.js

There was some code that was commented out that should be more performant and smaller than the existing code. This was done to avoid pulling in regenerator runtimes in the past but it seems this is no longer an issue and can be used without doing so.

use the commented out async code

---

src/TransWithoutContext.js
src/context.js
src/defaults.js
src/i18nInstance.js
src/useSSR.js
src/useTranslation.js
src/utils.js
src/withSSR.js
src/withTranslation.js

By converting all functions to arrow functions we optimize two things. First we can directly remove some return statements by using implicit return and secondly it allows bundlers to compress mupltiple const declarations into a single const declaration with multiple constants.
Example:
```js
const test1 = "test1"
const test2 = "test2"
const test3 = "test3"
```
Becomes
```js
const test1 = "test1", test2 = "test2", test3 = "test3"
```
Which saves some bytes that would otherwise be used for the function keyword in the pervious version.

use arrow functions where possible

---

src/TransWithoutContext.js
src/useTranslation.js
src/utils.js
test/utils.spec.js

Creates a simple `isString` helper function to avoid duplicated code when doing string checks.
It also adds the relevant tests for the new function.

create a isString helper to avoid code duplication

---

src/TransWithoutContext.js

Simplifies `hasValidReactChildren` a bit by utilizing Array.isArray, implicit returns and the fact that `.every()` can take a function without arguments as it's own argument.
This no longer returns false when it's not an array but rather implicitly returns `undefined` which don't affect current functionality as the code it's used in just checks for truthy values.

Simplifies hasValidReactChildren

---

src/TransWithoutContext.js

Some small optimizations inside nodesToString to reduce code size and duplication.

optimize_nodesToString

---

src/TransWithoutContext.js
src/useTranslation.js
src/utils.js
test/utils.spec.js

Creates a isObject helper function to reduce code duplication.
Also includes the relevant tests.

create a isObject helper function

---

example/react-component-lib/README.md
example/react-localstorage/README.md
example/react/README.md
example/v9.x.x/react-fluent/README.md
example/v9.x.x/react-icu/README.md
example/v9.x.x/react/README.md
icu.macro.d.ts
index.d.ts
package-lock.json
package.json

Let's start the new major version with an upgrade to most dependencies, this resolves the major vulnerabilities in the repo and ensures that the build configs are up to date.

some dependency updates

---

package.json
src/Translation.js
src/utils.js
tsconfig.json

Changes the `BABEL_ENV` from `jsnext` to `ESNext` which should give the intended effects for es modules, this allows const functions to be used more without breaking the optimisations. 
It also changes the targets and libs in tsconfig to match the minimum version needed for optional chaining to function (ES2020).

Build config and optimizations

---

vitest.workspace.typescript.mts

After #1769 typescript tests are broken:
- PR check actions: https://github.com/i18next/react-i18next/actions/runs/9955337360/job/27502861502
- Ci commit on master: https://github.com/i18next/react-i18next/actions/runs/9955483146/job/27503339706
Applied the same configuration of `i18next` (https://github.com/i18next/i18next/pull/2210)

test(types): fix broken tests

---

lint-staged.config.mjs
package-lock.json
package.json

Fixes the lint-staged config to remove this warning:

fix: lint-staged config

---

.husky/pre-commit
package-lock.json
package.json

### Description 
Upgrade husky to v9, along with its config.

chore: upgrade husky to v9

---

.eslintignore
.eslintrc.json
icu.macro.js
lint-staged.config.mjs
package.json
test/.eslintrc.json

ESLint will now run on commit alongside Prettier and will no longer ignore TS files.

fix: eslint config

---

lint-staged.config.mjs

### Description
Adds the `--ignore-unknown` flag when running Prettier from lint-staged, which was accidentally missing from #1779.

fix: lint-staged prettier command

---

package-lock.json
package.json
test/__snapshots__/icu.macro.spec.js.snap
test/icu.macro.spec.js

Updates babel-plugin-tester to the latest version (v11).

chore: update babel-plugin-tester to v11

---

.eslintrc.json
src/TransWithoutContext.js
test/icu.macro.spec.js

Address the ESLint error introduced in #1790. I was unable to understand why it was happening so I opted to add an ignore to it to unblock master.

fix: eslint import/no-unresolved error

---

.eslintrc.json
package-lock.json
package.json

Updates eslint-plugin-testing-library to v6.
Disables the [`testing-library/no-manual-cleanup`](https://github.com/testing-library/eslint-plugin-testing-library/blob/main/docs/rules/no-manual-cleanup.md) rule, which is now active by default on the `testing-library/react` config, because vitest doesn't expose global `afferEach` methods. 
_Note_: The lint step in failing in CI for an unrelated reason, which is fixed in #1791.

chore: update eslint-plugin-testing-library to v6

---

README.md

The link to the v9 example in your current README.md is incorrect. 404
[v9 examples](https://github.com/i18next/react-i18next?tab=readme-ov-file#v9-samples)

docs: Update v9 example link

---

src/TransWithoutContext.js

fix: Attempted to assign to readonly property

---

react-i18next.js
src/TransWithoutContext.js
test/trans.render.spec.jsx

fix issue 1815

---

src/TransWithoutContext.js

@adrai @aiktb @XAOPT When I made the changes in https://github.com/i18next/react-i18next/pull/1813 I wasn't aware of the conditional return, It seems in the example provided here: https://stackblitz.com/edit/vitejs-vite-59g4bx?file=package.json the first [if statement](https://github.com/i18next/react-i18next/blob/master/src/TransWithoutContext.js#L367-L372) in `TransWithoutContext` is returning void causing the unmodified components (without key) to get rendered.
That function handles both arrays and objects using `Object.keys` which is smart but also very confusing. We could revert my changes and the warning will disappear but it will cause errors to show up because those components are readonly, also as specified here in your type: …

Fix: warning each child should have a unique key

---

TransWithoutContext.d.ts
index.d.ts
src/TransWithoutContext.js
src/useTranslation.js
src/utils.js

feat:  add meta with codes on warnings to allow conditional logging

---

src/TransWithoutContext.js

Fixes the unique key warning that occurs with React 19 when the `Trans` component was used with elements with children. The created `Componentized` element didn't include the original key.
Fixes #1834

fix: unique key warning on componentized element

---

index.d.ts
package.json

TypeScript 5.0 has introduced [const type parameters][1]. These indicate that a more specific type is preferred over a more general one. As a result, the resulting UseTranslationResponse will be more precise and retain the passed-in namespace and prefix. This can be used by extractors and other tooling to find out exactly which key is accessed by a translation function call.
[1]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters

feat: use const type parameters for useTranslation()

---

package-lock.json
package.json

Follow up of https://github.com/i18next/react-i18next/pull/1842 and https://github.com/i18next/react-i18next/commit/ac79767b39fa0baec421b35a430ab73e80a253aa .
@emersion `peerDependencies` and `peerDependenciesMeta` were already present in the `package.json`, 
you duplicated the keys. 
Also remember to run `npm i` after editing `package.json` dependencies related entires.
@adrai you merged the PR and removed the duplicated entries without adding typescript in https://github.com/i18next/react-i18next/commit/ac79767b39fa0baec421b35a430ab73e80a253aa .

add typescript as optional peer dependency

---

src/TransWithoutContext.js

Since React v19 element.ref access is deprecated and will log an error message when done. This small PR fixes this issue in backwards compatible fashion.
https://react.dev/blog/2024/04/25/react-19-upgrade-guide#deprecated-element-ref

Fix element.ref access issue with react 19

---

package-lock.json
package.json

The current version of @babel/runtime contains a security vulnerability. Updating to 7.26.10 fixes this.

chore: update @babel/runtime to 7.26.10

---

index.d.ts

Hello,
I have updated to v15.7.0, but I encountered a case where type inference with `useTranslation()` does not work correctly.
In my project, I am using i18next v25.3.x.
(I am aware that updating to v25.4 would resolve the issue.)
Since `enableSelector` is not defined in `TypeOptions`, type inference is failing.
Looking at the peerDependencies, I noticed that `"i18next": ">= 23.2.3"` is specified.
Considering compatibility, I thought it would be appropriate to handle cases where `enableSelector` is not present in `TypeOptions`, so I made this PR.
Thank you for your consideration.

Fix: `_EnableSelector` type (for compatibility, enableSelector does not exist in TypeOptions)
