i18next/react-i18next

README.md
=> better example for <Interpolate>

README.md
Following issue https://github.com/i18next/react-i18next/issues/83
=> getWrappedInstance() clean example

package.json, src/translate.js
Thisi is what [react-redux](https://github.com/reactjs/react-redux) `connect`, and other `HoC` do.
=> Hoist non react statics

.travis.yml, __tests__/i18nextProvider-test.js, __tests__/interpolate-test.js, __tests__/loadNamespaces-test.js, __tests__/translate-test.js, package.json, src/I18nextProvider.js
=> test: add tests setup + coverage + travis

example/app/main.js
Refactors the example's main script to reflect the documentation provided in /README.md
=> Refactor /example/app/main.js

README.md
this will allow syntax highlighting
=> chore(README): add typescript flag to the code block

src/trans.js, test/trans.render.spec.js
=> Make Trans parent element configurable.

src/Trans.js, test/trans.render.spec.js
=> Render empty string on empty string as Trans child.

.travis.yml, package.json, test/setup.js, test/trans.render.spec.js
Added `enzyme-adapter-react-helper` to support multiple versions of React (0.14, 15, 16).
Also configured matrix jobs for Travis.
=> Improved tests system

example/storybook/.storybook/config.js, example/storybook/package.json, example/storybook/stories/index.js
`@kadira/storybook` renamed `@storybook/react`
=> Replace @kadira/storybook to @storybook/react

example/razzle-ssr/.babelrc, example/razzle-ssr/.gitignore, example/razzle-ssr/package.json, example/razzle-ssr/src/Home.js, example/razzle-ssr/src/i18n.js, example/razzle-ssr/src/locales/en/translations.json, example/razzle-ssr/src/server.js
i18next/react-i18next#485
1. Update dependencies
1. Make `wait` option gloabl
1. FIX Razzle server config which was missing locales files
=> DRY i18next/react-i18next#485

README.md, example/locize/README.md
Just fix path for video thumbnail
=> Fix video.png path

example/nextjs/package.json, example/nextjs/pages/_app.js, example/nextjs/server.js
https://github.com/i18next/react-i18next/issues/554
=> Use localStorage and cookie for caching locale

example/nextjs/pages/_app.js
Reverts i18next/react-i18next#580
=> Revert "nextjs example page3 ssr rendering fix"

example/nextjs/i18n.js
Just noticed this... Simple mistake.
=> Swap comment typo

example/reactnative-expo/.babelrc, example/reactnative-expo/app.json, example/reactnative-expo/babelrc.config.js, example/reactnative-expo/js/i18n.js, example/reactnative-expo/package.json
version up reactnative-expo expo to 31 as this version remove Localization has been removed from Dangerzone.
=> version up expo to 31

hooks.d.ts
The file index.d.ts have been moved
=> Fix hooks.d.ts

.prettierrc, hooks.d.ts, package.json, src/index.d.ts, test/typescript/NamespacesConsumer.test.tsx, test/typescript/examples-react.test.tsx, tsconfig.json, tslint.json
No actual ts changes other than prettier having been run.
=> Sync typescript setup with i18next using dtslint and prettier 

src/index.d.ts, test/typescript/withNamespaces.test.tsx
Fixes #676 
- Add test file for withNamespaces HOC
=> Fix WithNamespacesOptions `wait` requirement

package.json, test/typescript/GenericTranslateFunction.test.tsx
Depends on https://github.com/i18next/i18next/pull/1180
=> TS generics fixes related to i18next/1180

src/Translation.js, src/index.d.ts, test/typescript/Translation.test.tsx
=> Add typescript for Translation component - clarify options, simplify redundant use of t

src/context.js, src/useTranslation.js
Id like to listen to store changes and rerender if this occurs. This is nice if you change namespace values over time :)
=> Add bindI18nStore event options to listen to store changes if needed.

test/typescript/examples.test.tsx, test/typescript/withTranslation.test.tsx
- split test
- expand test with required prop
/related #746
=> Proof of withTranslation behavior with props

CHANGELOG.md, package.json, src/index.d.ts
Updated TS definitions UseTranslationOptions interface with useSuspense configuration boolean. 
Updated patch version and changelog description.
=> Updated TS definitions

src/useTranslation.js, test/useTranslation.spec.js
Solves #820 allowing to look for translation in all specified namespaces.
=> nsMode option is added to fallback namespaces

src/useSSR.js
=> Fix conditional usage of hooks error

.eslintignore, test/typescript/nonEsModuleInterop/examples.test.tsx, test/typescript/useTranslation.test.tsx
Try to assert issue reported in #954
=> Test exposed i18n types

package.json
PR following discussions on #954 with @rosskevin
=> update peer dependency to fix typescript issue

src/index.d.ts, test/typescript/i18n.ts, test/typescript/withTranslation.test.tsx
Closes #1006
Optional props documented 
- https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense
- https://react.i18next.com/latest/withtranslation-hoc#overriding-the-i-18-next-instance
are now exposed.
=> Extend withTranslation tests to include optional props

src/index.d.ts, test/typescript/Trans.test.tsx, test/typescript/withTranslation.test.tsx
=> Allow html props on Trans, fix `parent` prop type

example/razzle-ssr/package.json, example/razzle-ssr/src/i18n.js, example/react-icu/package.json, example/react-icu/src/i18n.js, example/react/package.json, example/react/src/i18n.js, example/storybook/package.json, example/storybook/src/i18n.js, example/test-jest/package.json, example/test-jest/src/i18n.js, example/v9.x.x/dat/package.json, example/v9.x.x/dat/src/i18n.js, example/v9.x.x/preact/package.json, example/v9.x.x/preact/src/i18n.js, example/v9.x.x/razzle-ssr/package.json, example/v9.x.x/razzle-ssr/src/i18n.js, example/v9.x.x/react-icu/package.json, example/v9.x.x/react-icu/src/i18n.js, example/v9.x.x/react/package.json, example/v9.x.x/react/src/i18n.js, example/v9.x.x/test-jest/package.json, example/v9.x.x/test-jest/src/i18n.js
**merge only, when i18next-http-backend is published**
=> replace xhr backend with new http backend

test/trans.nodeToString.spec.js
=> test(nodesToString): replace manual object with proper JSX

example/react/public/locales/de/translation.json
Fix the grammar of the german translation referenced in the Step-by-step guide
=> example translation json: Fix german grammar

react-i18next.js, src/Trans.js, src/useTranslation.js
A small pull request (if required) to update the i18next instance warnings in the various files since I spotted them whilst running tests.
=> Update i18next instance warnings

src/ts4.1/index.d.ts
Fix issues: https://github.com/i18next/react-i18next/issues/1217 and https://github.com/i18next/react-i18next/issues/1218
=> fix: type definitions for typescript 4.1

src/ts4.1/index.d.ts
Fix new issues reported here: https://github.com/i18next/react-i18next/issues/1217
=> Fix: Return type inference for t function (typescript 4.1)

src/ts4.1/index.d.ts
Fix issue: https://github.com/i18next/react-i18next/issues/1215
=> fix: Inference for specific keys ts 4.1

src/useTranslation.js
=> warn for old wait usage

example/react/README.md
Fixed 3 typos inside README react example.
=> Fixed typo

README.md
Hi i18next team,
I was browsing through the README and noticed a broken/outdated link. This PR is to simply replace the previous link with a similar and more recent article I found from codetain.
=> Update codetain link

example/razzle-ssr/src/i18n.js, example/razzle-ssr/src/server.js
=> Improved razzle-ssr example

test/typescript/custom-types/custom-types.d.ts, test/typescript/custom-types/useTranslation.test.tsx, ts4.1/index.d.ts
Closes https://github.com/i18next/react-i18next/issues/1386 and https://github.com/i18next/i18next/issues/1683
=> Add type support to plurals

ts4.1/index.d.ts
Closes https://github.com/i18next/react-i18next/issues/1401
=> Rollback changes made on PR #1400

index.d.ts, ts4.1/index.d.ts
Closes https://github.com/i18next/react-i18next/issues/1428 and https://github.com/i18next/react-i18next/issues/1427
=> Add missing types

index.d.ts, package-lock.json, package.json, ts4.1/index.d.ts, tsconfig.json, tslint.json
=> Fixes #1418

ts4.1/index.d.ts
Closes https://github.com/i18next/react-i18next/issues/1451
=> Fix never return type when using plurals

src/Trans.js, test/trans.nodeToString.spec.js, test/trans.render.spec.js
fix based on @jamuhl suggestion in #1468
=> fix based on @jamuhl suggestion in #1468

package.json
Removed useless husky hooks from `package.json` file (already declared in `.husky` folder)
=> Removed useless husky hooks from `package.json` file

index.d.ts
Pending https://github.com/i18next/i18next/pull/2122 to update i18next in `peerDependencies` and `devDependencies`
=> types: fix typo in `CustomInstanceExtensions`

CHANGELOG.md
Fix a minor typo in the Change Log
=> fix: minor typo in CHANGELOG.md

src/TransWithoutContext.js
close https://github.com/i18next/react-i18next/issues/1805
=> fix:  `<Trans />` warns 'Each child in a list should have a unique "key" prop.'

index.d.ts
Closes #1861 
Related to #1860
=> chore: exports `TransSelectorProps`
